/**
 * Where the Record keeps material that is not text.
 *
 * Two rules shape this module:
 *
 *   * **Paths are stored relative.** iOS rewrites the app container's absolute path on
 *     reinstall and on some restores, so an absolute `file:///.../Documents/audio/x.m4a`
 *     recorded today can be wrong tomorrow while the file itself is perfectly fine. The
 *     database holds `audio/x.m4a`; this module joins it to wherever the container is now.
 *   * **Nothing here is allowed to take the app down.** A full volume, a revoked container,
 *     a web target with no filesystem at all — each returns a miss, and the caller says so
 *     honestly (`audio_missing`, an archive still owed) rather than crashing or pretending.
 */

import { Directory, File, Paths } from 'expo-file-system';

/** Everything the Record writes lives under this one directory inside Documents. */
const ROOT = 'chinotto';
/** Retained voice audio. Canonical material: this is the source a transcript is derived from. */
export const AUDIO_DIR = `${ROOT}/audio`;

/** True when this build actually has a document directory to write into. */
export function hasFileSystem(): boolean {
  try {
    return typeof Paths.document?.uri === 'string' && Paths.document.uri.length > 0;
  } catch {
    return false;
  }
}

function ensureDirectory(relativeDir: string): Directory | null {
  try {
    const dir = new Directory(Paths.document, relativeDir);
    if (!dir.exists) {
      dir.create({ intermediates: true, idempotent: true });
    }
    return dir;
  } catch {
    return null;
  }
}

/**
 * Resolves a stored relative path to an absolute `file://` URI for this launch.
 * Returns null when there is no filesystem; never throws.
 */
export function resolveRecordUri(relativePath: string): string | null {
  try {
    return new File(Paths.document, relativePath).uri;
  } catch {
    return null;
  }
}

/** True when the material behind a stored relative path is still on disk. */
export function recordFileExists(relativePath: string): boolean {
  try {
    return new File(Paths.document, relativePath).exists;
  } catch {
    return false;
  }
}

/** Size in bytes, or null when the file is gone or unreadable. */
export function recordFileSize(relativePath: string): number | null {
  try {
    const file = new File(Paths.document, relativePath);
    return file.exists ? (file.size ?? null) : null;
  } catch {
    return null;
  }
}

/**
 * Writes text under the Record's directory and returns the RELATIVE path it was stored at.
 * Throws on failure, so callers can decide whether the write was load-bearing.
 */
export async function writeRecordText(fileName: string, contents: string): Promise<string> {
  const relative = `${ROOT}/${fileName}`;
  if (!ensureDirectory(ROOT)) {
    throw new Error('[Record] no document directory to write into');
  }
  const file = new File(Paths.document, relative);
  if (!file.exists) {
    file.create({ intermediates: true, overwrite: true });
  }
  file.write(contents);
  return relative;
}

/** Makes sure the audio directory exists. Returns false when it could not be created. */
export function ensureAudioDirectory(): boolean {
  return ensureDirectory(AUDIO_DIR) !== null;
}

/** The relative path a voice capture's audio should be stored at. */
export function audioPathFor(fragmentId: string, extension = 'm4a'): string {
  // Fragment ids are generated by us (uuid / n<seq>_<ts>), but a legacy or imported id could
  // carry anything. Anything that is not plainly safe in a path is replaced rather than
  // escaped, because the id in the database is the identity — the filename is only a label.
  const safe = fragmentId.replace(/[^A-Za-z0-9._-]/g, '_');
  return `${AUDIO_DIR}/${safe}.${extension}`;
}

/** A retained recording's path, as this module writes them: one plain file in `AUDIO_DIR`. */
const RETAINED_AUDIO = /^chinotto\/audio\/[A-Za-z0-9_-][A-Za-z0-9._-]*\.m4a$/;

/** True for a path that is plainly one of the Record's own recordings, and nothing else. */
export function isRetainedAudioPath(relativePath: string): boolean {
  return RETAINED_AUDIO.test(relativePath) && !relativePath.includes('..');
}

/**
 * Deletes retained audio. Returns true when something was deleted.
 *
 * Called when a recording is too short to keep, and when a removal can no longer be brought
 * back (`record/erasure.ts`) — never during the undo window, and never on a transcription
 * failure. Refuses anything that is not plainly a file in `AUDIO_DIR`: a path comes from the
 * database, and the database is not a reason to delete something elsewhere.
 */
export function deleteRecordFile(relativePath: string): boolean {
  if (!isRetainedAudioPath(relativePath)) return false;
  try {
    const file = new File(Paths.document, relativePath);
    if (!file.exists) return false;
    file.delete();
    return true;
  } catch {
    return false;
  }
}

/**
 * Every file in the audio directory, as relative paths. Null when the directory cannot be
 * read — which is not the same as empty, and callers must not treat it as such.
 */
export function listRetainedAudio(): string[] | null {
  try {
    const dir = new Directory(Paths.document, AUDIO_DIR);
    if (!dir.exists) return [];
    return dir
      .list()
      .filter((entry): entry is File => entry instanceof File)
      .map((file) => `${AUDIO_DIR}/${file.name}`);
  } catch {
    return null;
  }
}
